//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evaluacion3finalfinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public string nombre { get; set; }
        public Nullable<int> telefono { get; set; }
        public string email { get; set; }
        public string mensaje { get; set; }
        public int id { get; set; }
    }
}
